name: Release version with Debian packages

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on push tags like v1.0, v1.1, etc.

jobs:
  build-debian-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build .deb files
      run: make debian-docker

    - name: Upload Debian Package
      uses: actions/upload-artifact@v2
      with:
        name: debian-packages
        path: ./dist_deb/*.deb

  create-release:
    needs: build-debian-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: debian-packages
          path: dist_deb

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist_deb/*.deb
